builds:
  - main: cmd/cfs/main.go
    binary: cfs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
