builds:
  - main: ./cmd/cfs
    binary: cfs
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archives:
  - id: default
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
