# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/haramako/cfs
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - add_ssh_keys:
          fingerprints:
            - "1e:6f:bb:d4:dd:81:6e:4c:64:58:94:1f:59:73:05:ab"
      - deploy:
          name: goreleaser
          command: |
            if [[ -n ${CIRCLE_TAG} ]]; then
              curl -sL https://git.io/goreleaser | bash
            fi
deployment:
  trigger_tag:
    tag: /.*/
