# Golang CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/golang:1.14
  working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  deploy:
    <<: *defaults
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "31:c8:3b:93:3a:b9:d6:f2:b3:a3:a1:70:c4:3c:bd:3f"
      - run: |
          if [[ -n ${CIRCLE_TAG} ]]; then
            curl -sL https://git.io/goreleaser | bash
          fi

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /v.*/
